### ISSUE TITLE
Phone Menu and Disabling Tags

### ISSUE THREAD

**Issue by kvnandula04** [aemi-dev/aemi-wp#17]
Hi,

Excellent theme by the way! But just a few doubts...

When I load this theme on a mobile, the menubar is on the bottom of the phone instead of the top. How can I change it so that it's at the top?

Also, is there a way to hide tags from showing in posts?

Thanks in advance,
kvnandula04

**Comment by aemi-dev** [comment]
Hi @kvnandula04 ,

Thanks for reaching me ! 

These behaviours could be change through Theme Customizer.

For the header : Customizer > Aemi > Header > Header Stickyness : Select "Keep the header to the top of the view", then save your edit

For avoiding displaying tags in post : Customizer > Aemi > Type : Post > Uncheck Tags or Categories or whatever you want.

That's it.

Also if you like Aemi, please feel free to leave a comment on [Aemi WordPress Repository page](https://wordpress.org/support/theme/aemi/reviews/) or to star this repo !

Best Regards,
Guillaume

**Comment by kvnandula04** [comment]
Wow, thanks a lot for this! That helps!

**Comment by aemi-dev** [comment]
I'm glad it helped you @kvnandula04 !
